using Stethoscope.Common;

using System.IO;

namespace Stethoscope.Printers.Internal.PrintMode
{
    /// <summary>
    /// Ordered list of processaable print mode values.
    /// </summary>
    public class PrintModeFormat
    {
        //TODO

        /// <summary>
        /// Set the print mode value to use. This will reset any existing print mode values.
        /// </summary>
        /// <param name="mode">The print mode to use.</param>
        public void SetMode(string mode)
        {
            //TODO
        }

        /// <summary>
        /// Process an individual log with the stored print mode values.
        /// </summary>
        /// <param name="writer">The writer to write to.</param>
        /// <param name="log">The log to process.</param>
        /// <param name="state">The state generated by <see cref="GenerateStateObject"/></param>
        public void ProcessLog(TextWriter writer, ILogEntry log, object state)
        {
            //TODO
            /*
             * 1. evaluate log-level conditional
             * 2. Iterate over all format parts
             * 3. Execute part
             *     a. If raw, print. If not raw, evaluate conditional
             *     b. if conditional passes, print value (using modifiers if need-be) and notify conditional
             *     c. FUTURE-TODO: if conditional fails, and a failed conditional modifier exists, invoke it
             *     d. if exception occurs, invoke failure handler modifier if it exists
             */
        }

        /// <summary>
        /// Generate the state values necessary for <see cref="ProcessLog(TextWriter, ILogEntry, object)"/> to run.
        /// </summary>
        /// <returns>Generated state object.</returns>
        public object GenerateStateObject()
        {
            //TODO
            return null;
        }
    }
}
