@startuml

title LINQ Processing

[*] --> Uninitialized
Uninitialized --> CanProcessExpression

state ProcessSkip
CanProcessExpression --> ProcessSkip : Has Unprocessed\nSkip Expressions

state "Process Skip" as ProcessSkip {
  SetupProcessing --> MethodCollection : Invoke

  MethodCollection --> VisitExpressionTree : Invoke
  VisitExpressionTree --> MethodCollection : Done

  MethodCollection --> FindProcessingRange : Has Methods
  MethodCollection --> ReturnNull : No Methods
  
  FindProcessingRange --> CountAndRemoveSkips : Has Methods
  FindProcessingRange --> ReturnNull : No Methods
  
  CountAndRemoveSkips --> VisitExpressionTree : Invoke
  VisitExpressionTree --> CountAndRemoveSkips : Done

  CountAndRemoveSkips --> ReturnCountAndTree : Done
  
  ReturnNull --> DoneProcessing : Done
  ReturnCountAndTree --> DoneProcessing : Done
}

ProcessSkip --> CanProcessExpression : Done

CanProcessExpression --> ProcessSomething : Has Unprocessed\n<name> Expressions
ProcessSomething --> CanProcessExpression : Done

CanProcessExpression --> ReturnExpression : No More Expressions\nto process
ReturnExpression --> [*]

@enduml