@startuml

title Print Mode Format

[*] --> Uninitialized
Uninitialized --> Setup

Setup --> Setup
Setup --> LogConditional

LogConditional --> LogConditional
LogConditional --> Part

Part --> Raw
Part --> Attribute
Part --> DoneParsing

Raw --> Part

Attribute --> Conditional
Attribute --> AttributeReference

Conditional --> Conditional
Conditional --> AttributeReference

AttributeReference --> AttributeFormat
AttributeReference --> Modifier

AttributeFormat --> Modifier
' is this needed?
AttributeFormat --> StringQuote : Found a quote in string\nis this the end or a sub-string/random quote

Modifier --> Modifier
Modifier --> FinalizePart

FinalizePart --> Part

' TODO
Modifier --> ErrorHandlerModifier : Attribute Conditional
ErrorHandlerModifier --> Modifier : Attribute Conditional

ErrorHandlerModifier --> StringQuote : Found a quote in string\nis this the end or a sub-string/random quote

StringQuote --> AttributeFormat : Done processing attribute format
StringQuote --> ErrorHandlerModifier : Done processing error handler

DoneParsing --> [*]

@enduml